### ISSUE TITLE
Lambda deploy giving error

### ISSUE THREAD

**Issue by timbo256** [joseph-holland/lambda-graffiti-monkey#13]
When try to run the lambda deploy command I get the following error stack:

(graffiti-monkey) ubuntu@ip-10-186-101-166:~/lambda-graffiti-monkey$ lambda deploy
Gathering pip packages
Traceback (most recent call last):
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/bin/lambda", line 53, in <module>
    cli()
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/bin/lambda", line 39, in deploy
    aws_lambda.deploy(CURRENT_DIR, local_package)
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/local/lib/python2.7/site-packages/aws_lambda/aws_lambda.py", line 83, in deploy
    path_to_zip_file = build(src, local_package)
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/local/lib/python2.7/site-packages/aws_lambda/aws_lambda.py", line 175, in build
    pip_install_to_target(path_to_temp, local_package)
  File "/home/ubuntu/lambda-graffiti-monkey/graffiti-monkey/local/lib/python2.7/site-packages/aws_lambda/aws_lambda.py", line 247, in pip_install_to_target
    for r in pip.operations.freeze.freeze():
AttributeError: 'module' object has no attribute 'operations'

**Comment by joseph-holland** [comment]
Hi @timbo256 ,
You don't actually need to install it locally and then deploy, you can get up and running quickly by using the pre-created lambda deployment package in the releases section, [here](https://github.com/joseph-holland/lambda-graffiti-monkey/releases).

You can simply download the .zip and upload this source package to Lambda, then define the required environment variables.  Let me know if this works for you.

I have the additional install info mainly for people wishing to run it locally and for development.  I will update the documentation to make this clearer and easier for people to get up and going quicker.

-Joe

**Comment by timbo256** [comment]
Thanks Joe - will give it a try.
What events actually invoke the Lambda function or do we just create a Cloudwatch rule to create a schedule?
Ran it manually using the test function and it seemed to work except for the SNS part failing because of role permissions issues - which I am sure I can resolve!

**Comment by joseph-holland** [comment]
Nothing invokes it. Yes, a CloudWatch Events scheduled rule with the Lambda function as the target is what I've used.

I may have some Terraform code here somewhere that I've used to set this up in my personal AWS account. I'll upload something soon so you can see how I put it into action.

**Comment by timbo256** [comment]
Thanks Joe. It is now working fine as a Cloudwatch event. Really good for identifying 'orphaned' EBS volumes!

**Comment by ohaiwalt** [comment]
@joseph-holland Just stumbled across this, really interested in seeing that Terraform code if you've got it handy. Thanks for this lambda!

**Comment by joseph-holland** [comment]
Hi @ohaiwalt ,
I'll try get the Terraform code up this week.
Joe

**Comment by joseph-holland** [comment]
@ohaiwalt - I've uploaded the Terraform code here: https://github.com/joseph-holland/lambda-graffiti-monkey-terraform

Hope this helps!

Joe
